services:
  go-cron-app:
    build:
      context: .
      dockerfile: Dockerfile
    # Explicitly name the image to avoid the default "project-service" naming
    image: go-cron-be:latest  
    container_name: go-cron-be
    restart: unless-stopped
    
    # Environment variables
    env_file:
      - .env
    
      
    # Map port (if your app serves HTTP in the future)
    ports:
      - "8005:8005"
    
    # Use existing network
    networks:
      - go-oracle-network
    
    # Resource limits (optional)
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  go-oracle-network:
    external: true